import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import { Toaster } from "@/components/ui/sonner";
import { ReactLenis } from "@/components/providers/lenis-provider";
import { NextThemeProvider } from "@/components/providers/next-themes-provider";
import { EdgeStoreProvider } from "@/components/providers/edgestore-provider";
import { NotificationProvider } from "@/components/providers/notification-provider";
import "./globals.css";

const polySansBulky = localFont({
  src: "./fonts/PolySans-Bulky.woff2",
  variable: "--font-polySansBulky",
  display: "swap",
});

const polySansMedian = localFont({
  src: "./fonts/PolySans-Median.woff2",
  variable: "--font-polySansMedian",
  display: "swap",
});

const polySans = localFont({
  src: "./fonts/PolySans-Neutral.woff2",
  variable: "--font-polySans",
  display: "swap",
});

const polySansSlim = localFont({
  src: "./fonts/PolySans-Slim.woff2",
  variable: "--font-polySansSlim",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Elysian Emporium Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis
      root
      options={{
        lerp: 0.05,
        duration: 3,
        wheelMultiplier: 0.5,
        touchMultiplier: 1,
        smoothWheel: true,
      }}
    >
      <html suppressHydrationWarning lang="en">
        <body
          className={`${polySansSlim.variable} ${polySans.variable} ${polySansMedian.variable} ${polySansBulky.variable} antialiased font-sans`}
        >
          <EdgeStoreProvider>
            <NextThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NotificationProvider>
                <NextSSRPlugin
                  routerConfig={extractRouterConfig(ourFileRouter)}
                />
                <Toaster theme="system" />
                {children}
              </NotificationProvider>
            </NextThemeProvider>
          </EdgeStoreProvider>
        </body>
      </html>
    </ReactLenis>
  );
}
